import { join, dirname } from 'path';
import { existsSync, writeFileSync, mkdirSync } from 'fs';
import type { Tool } from "@modelcontextprotocol/server";
import type { ToolContext, ToolResult } from '../types.js';
import { maybeWrapUntrusted } from '../core/untrusted-wrap.js';
import { textResult } from '../types.js';
import { requireProjectPath, resolveWithinRoot, normalizeUserProjectPath } from '../helpers.js';
import { executeGdscript, executeGdscriptTrusted, executeGdscriptRuntime } from '../gdscript-executor.js';
import { SCENE_TREE_HEADER, parseGdscriptResult, wrapAssertionCode, opsErrorResult, validateTimeout, escapeForGdLiteral } from './shared.js';
import { batchValidateScripts } from './validation.js';
import { sendToBridge, setBridgeProjectDir, BRIDGE_READ_ONLY_METHODS } from './game-bridge.js';
import { spawnGodot } from './spawn-helper.js';
import type { RiskLevel } from '../core/tool-registry.js';
import { handleBatchAction } from './batch-tools.js';
import { referenceSimScript, extractFrameMetricsScript } from './frame-verify/gdscripts.js';
import { classifyDegradation, type FrameMetrics } from './frame-verify/degradation.js';
import { createProofRun, cleanupProofRun, recordFrameBytes, type ProofRun } from './frame-verify/proof-bundle.js';

// ─── Constants ─────────────────────────────────────────────────────────────

const ACTIONS = ['dev_loop', 'scene_snapshot', 'batch_validate', 'create_files', 'run_verify', 'diff_scenes'] as const;

// ─── Session State helpers (file-as-memory pattern) ──────────────────────────

export interface SessionState {
  current_task: string;
  epic?: string;
  feature?: string;
  files_modified?: string[];
  decisions?: string[];
  open_questions?: string[];
}

export function formatSessionState(state: SessionState): string {
  const lines: string[] = [
    `# Session State`,
    ``,
    `> Auto-generated by dev_loop save_state`,
    ``,
    `## Current Task`,
    ``,
    state.current_task,
    ``,
  ];

  if (state.epic || state.feature) {
    lines.push(`## Context`);
    lines.push(``);
    if (state.epic) lines.push(`- **Epic**: ${state.epic}`);
    if (state.feature) lines.push(`- **Feature**: ${state.feature}`);
    lines.push(``);
  }

  if (state.files_modified && state.files_modified.length > 0) {
    lines.push(`## Files Modified`);
    lines.push(``);
    for (const f of state.files_modified) lines.push(`- \`${f}\``);
    lines.push(``);
  }

  if (state.decisions && state.decisions.length > 0) {
    lines.push(`## Key Decisions`);
    lines.push(``);
    for (const d of state.decisions) lines.push(`- ${d}`);
    lines.push(``);
  }

  if (state.open_questions && state.open_questions.length > 0) {
    lines.push(`## Open Questions`);
    lines.push(``);
    for (const q of state.open_questions) lines.push(`- [ ] ${q}`);
    lines.push(``);
  }

  return lines.join('\n');
}

export function buildStateBlock(epic: string, feature: string, task: string): string {
  const lines = ['<!-- STATUS -->'];
  if (epic) lines.push(`Epic: ${epic}`);
  if (feature) lines.push(`Feature: ${feature}`);
  if (task) lines.push(`Task: ${task}`);
  lines.push('<!-- /STATUS -->');
  return lines.join('\n');
}

// ─── Tool definitions ──────────────────────────────────────────────────────

export function getToolDefinitions(): Tool[] {
  return [
    {
      name: 'workflow',
      description: '开发工作流工具。dev_loop: 执行 GDScript,可选项目验证/bridge 截图查询/验收断言/状态保存。scene_snapshot: 结构化场景树快照。batch_validate: 批量验证多个脚本。',
      inputSchema: {
        type: 'object' as const,
        properties: {
          project_path: { type: 'string', description: 'Godot 项目目录路径（可选，默认使用 GODOT_PROJECT_PATH 环境变量或当前目录）' },
          action: {
            type: 'string',
            enum: [...ACTIONS],
            description: '操作类型。dev_loop=执行+验证一体, scene_snapshot=场景树快照, batch_validate=批量脚本验证',
          },
          // dev_loop params
          code: { type: 'string', description: 'dev_loop: 要执行的 GDScript 代码(片段或完整 extends SceneTree)' },
          verify: { type: 'boolean', description: 'dev_loop: 执行后是否跑项目验证(默认 false)', default: false },
          timeout: { type: 'number', description: 'dev_loop: 每步超时秒数(默认 30)', default: 30 },
          load_autoloads: { type: 'boolean', description: 'dev_loop: 是否加载 Autoload 上下文(默认 true)', default: true },
          bridge: {
            type: 'object',
            description: 'dev_loop: 可选 Game Bridge,代码执行后截图/查询验证',
            properties: {
              screenshot: {
                type: 'object',
                description: '从运行中的游戏截图',
                properties: {
                  path: { type: 'string', description: '游戏内截图保存路径(默认 user://mcp_dev_screenshot.png)' },
                },
              },
              queries: {
                type: 'array',
                maxItems: 10,
                description: '代码执行后要跑的 bridge 查询(最多 10 条)',
                items: {
                  type: 'object',
                  properties: {
                    method: { type: 'string', description: 'bridge 查询方法名' },
                    params: { type: 'object', description: '查询参数' },
                    expect: { type: 'string', description: '期望结果子串(可选)' },
                  },
                  required: ['method'],
                },
              },
            },
          },
          acceptance: {
            type: 'object',
            description: 'dev_loop: 可选验收标准',
            properties: {
              assertions: {
                type: 'array',
                description: '代码执行后运行的断言数组',
                items: {
                  type: 'object',
                  properties: {
                    description: { type: 'string', description: '断言的可读描述' },
                    gdscript: { type: 'string', description: '用 _mcp_output 输出结果的 GDScript 代码' },
                    expect: { type: 'string', description: '期望输出值(字符串比较)' },
                    type: { type: 'string', description: '断言类型: gdscript(默认)/screenshot_diff/frame_degradation', enum: ['gdscript', 'screenshot_diff', 'frame_degradation'] },
                    expect_present: { type: 'array', items: { type: 'string' }, description: 'screenshot_diff: 场景树中应可见的节点名' },
                    reference_path: { type: 'string', description: 'screenshot_diff: 余弦相似度预筛的参考图路径(可选)' },
                    sim_threshold: { type: 'number', description: 'screenshot_diff: 余弦相似度阈值(默认 0.85)' },
                    frames_dir: { type: 'string', description: 'frame_degradation: 帧截图目录(acceptance.frame_sequence 捕获时可省略)' },
                  },
                  required: ['description'],
                },
              },
              frame_sequence: {
                type: 'object',
                description: '断言运行前捕获 N 帧到证据目录;帧供 frame_degradation 断言',
                properties: {
                  count: { type: 'number', description: '捕获帧数(2-60,默认 12)' },
                  interval_frames: { type: 'number', description: '~60fps 下每次捕获间隔帧数(1-300,默认 10)' },
                },
              },
            },
          },
          save_state: {
            type: 'object',
            description: 'dev_loop: 保存会话状态到文件',
            properties: {
              path: { type: 'string', description: '状态文件路径(相对项目,默认 production/session-state/active.md)' },
              task: { type: 'string', description: '当前任务描述' },
              epic: { type: 'string', description: 'Epic 名(可选)' },
              feature: { type: 'string', description: 'Feature 名(可选)' },
              files_modified: {
                type: 'array',
                description: '本次会话修改的文件清单',
                items: { type: 'string' },
              },
              decisions: {
                type: 'array',
                description: '关键决策记录',
                items: { type: 'string' },
              },
              open_questions: {
                type: 'array',
                description: '未解决问题',
                items: { type: 'string' },
              },
            },
          },
          // scene_snapshot params
          scene_path: { type: 'string', description: 'scene_snapshot: 场景文件路径(相对项目)' },
          max_depth: { type: 'number', description: 'scene_snapshot: 最大遍历深度(默认 5)', default: 5 },
          // batch_validate params
          scripts: {
            type: 'array',
            description: 'batch_validate: 脚本路径数组(相对项目)',
            items: { type: 'string' },
          },
          godot_path: { type: 'string', description: '覆盖 Godot 二进制路径（可选，优先于项目配置和环境变量）' },
        },
        required: ['action'],
      },
    },
  ];
}


// --- Tool handler ---------------------------------------------------------------

/**
 * scene_snapshot 生成的 GDScript 脚本。提取为函数便于单元测试 _root 判空守卫(CRITICAL 防回归)。
 * 行为与原内联 snapScript 等价(内容整体移入)。
 */
export function genSceneSnapshotScript(safePath: string, maxDepth: number): string {
  return `${SCENE_TREE_HEADER}

func _initialize():
\tvar packed := load("${safePath}")
\tif packed == null:
\t\t_mcp_output("error", "Failed to load scene: ${safePath}")
\t\t_mcp_done()
\t\treturn
\tvar instance: Node = packed.instantiate()
\tvar _root: Node = _mcp_get_root()
\tif _root == null:
\t\t_mcp_output("error", "Scene root not available")
\t\tinstance.queue_free()
\t\t_mcp_done()
\t\treturn
\t_root.add_child(instance)
\tvar data := _snap(instance, ${maxDepth}, 0)
\t_mcp_output("snapshot", data)
\tinstance.queue_free()
\t_mcp_done()

func _snap(node: Node, max_depth: int, depth: int) -> Dictionary:
\tvar info := {"name": node.name, "type": node.get_class()}
\tif node is Node2D:
\t\tinfo["position"] = {"x": node.position.x, "y": node.position.y}
\t\tinfo["rotation"] = node.rotation
\tif node is Node3D:
\t\tinfo["position"] = {"x": node.position.x, "y": node.position.y, "z": node.position.z}
\tif depth < max_depth:
\t\tvar ch: Array = []
\t\tfor c in node.get_children():
\t\t\tch.append(_snap(c, max_depth, depth + 1))
\t\tinfo["child_count"] = ch.size()
\treturn info
`;
}

/** A3: user:// res:// 分支 .. 段拒绝（对齐 command_helpers.gd has_path_traversal 语义）。
 * 统一 resolveWithinRoot 会破坏 user:// 语义（user:// 映射到 OS 用户数据目录非项目根），
 * 故最小补 .. 段拒绝：检测 /../ 、startsWith('../')、endsWith('/..')、=== '..' 四形。 */
function hasTraversalSegments(p: string): boolean {
  return p.includes('/../') || p.startsWith('../') || p.endsWith('/..') || p === '..';
}

export async function handleTool(name: string, args: Record<string, unknown>, ctx: ToolContext): Promise<ToolResult | null> {
  if (name !== 'workflow') return null;

  const action = args.action as string;
  if (!action) return opsErrorResult('INVALID_PARAMS', '"action" is required (dev_loop, scene_snapshot, or batch_validate).');

  switch (action) {

    case 'dev_loop': {
      const projectPath = requireProjectPath(args);
      const code = args.code as string;
      const verify = args.verify === true;
      const timeout = validateTimeout(args.timeout, 5, 120, 30);
      const loadAutoloads = args.load_autoloads !== false;

      if (!code || typeof code !== 'string') {
        return opsErrorResult('INVALID_PARAMS', '"code" must be a non-empty string.');
      }

      // Task 4: 算正常模式 total（execute 恒有 + verify/bridge/acceptance 条件性）。
      // 各阶段 index 按标志内联计算（避免可变计数器的 no-useless-assignment）：
      // execute=1, verify=2, bridge=willVerify?3:2, acceptance=total(末位)
      const willVerify = verify;
      const willBridge = !!(args.bridge && typeof args.bridge === 'object' && !Array.isArray(args.bridge));
      const willAccept = !!(args.acceptance && typeof args.acceptance === 'object' && !Array.isArray(args.acceptance));
      const total = 1 + (willVerify ? 1 : 0) + (willBridge ? 1 : 0) + (willAccept ? 1 : 0);

      // ── DSL detection: if all non-empty lines are valid DSL, run as Bridge sequence ──
      const codeLines = code.split('\n');
      const nonEmptyLines = codeLines.filter(l => l.trim().length > 0);
      const dslCommands = nonEmptyLines.map(l => parseE2eDsl(l));
      const allDsl = nonEmptyLines.length > 0 && dslCommands.every(c => c !== null && c.method !== '_error');

      if (allDsl) {
        if (projectPath) setBridgeProjectDir(projectPath);
        const dslTotal = dslCommands.length; // Task 4: DSL total = 命令数
        const dslResults: Array<{ command: string; success: boolean; error?: string }> = [];
        for (let i = 0; i < dslCommands.length; i++) {
          const cmd = dslCommands[i];
          if (!cmd) continue;
          ctx.progress?.(i + 1, dslTotal, cmd.method); // Task 4: 每命令前推
          if (cmd.method === '_sleep') {
            await new Promise<void>(r => setTimeout(r, (cmd.params.ms as number) || 100));
            dslResults.push({ command: `waitMs(${cmd.params.ms})`, success: true });
            continue;
          }
          try {
            const resp = await sendToBridge(cmd.method, cmd.params, 10000);
            dslResults.push({
              command: `${cmd.method}(${JSON.stringify(cmd.params)})`,
              success: !resp.error,
              error: resp.error?.message,
            });
          } catch (e: unknown) {
            dslResults.push({
              command: `${cmd.method}(${JSON.stringify(cmd.params)})`,
              success: false,
              error: (e as Error).message,
            });
          }
        }
        return textResult(JSON.stringify({ mode: 'dsl', results: dslResults }, null, 2));
      }

      ctx.progress?.(1, total, 'executing GDScript'); // Task 4: execute=步1
      const godot = await ctx.findGodot();
      const execResult = await executeGdscript({
        godotPath: godot,
        projectPath,
        code,
        timeout,
        loadAutoloads,
      });

      const result: Record<string, unknown> = {
        step1_execute: execResult.compile_success ? 'success' : 'compile_error',
      };

      if (!execResult.compile_success) {
        result.compile_error = execResult.compile_error;
        return textResult(JSON.stringify(result, null, 2));
      }

      if (!execResult.run_success) {
        result.step1_execute = 'runtime_error';
        result.run_error = execResult.run_error;
        return textResult(JSON.stringify(result, null, 2));
      }

      const outputs: Record<string, unknown> = {};
      for (const entry of execResult.outputs) {
        try {
          outputs[entry.key] = JSON.parse(entry.value);
        } catch {
          // P1-1: parse 失败的自由文本 = 游戏 stdout 自由 print(最典型注入载体),包 nonce 信封;
          // parse 成功的结构化值是哨兵标记提取的受控输出,不包(保格式)。折中见 untrusted-wrap.ts。
          outputs[entry.key] = maybeWrapUntrusted('workflow.execute', entry.key, entry.value);
        }
      }
      result.outputs = outputs;

      if (verify) {
        ctx.progress?.(2, total, 'verifying'); // Task 4: verify=步2
        result.step2_verify = await runVerification(godot, projectPath);
      }

      // ── Bridge step: connect to running game for screenshot/query ──
      const rawBridge = args.bridge;
      const bridge = (rawBridge && typeof rawBridge === 'object' && !Array.isArray(rawBridge))
        ? rawBridge as Record<string, unknown>
        : undefined;
      if (bridge) {
        ctx.progress?.(willVerify ? 3 : 2, total, 'bridge queries/screenshot'); // Task 4: bridge=步2或3
        if (projectPath) {
          setBridgeProjectDir(projectPath);
        }
        const bridgeResult: Record<string, unknown> = { connected: false };
        try {
          // Ping first to verify connectivity
          const pingResp = await sendToBridge('ping', {}, 5000);
          if (pingResp.error) {
            bridgeResult.error = `Bridge ping failed: ${pingResp.error.message}`;
          } else {
            bridgeResult.connected = true;

            // Screenshot
            const screenshot = bridge.screenshot as Record<string, unknown> | undefined;
            if (screenshot) {
              const rawPath = (screenshot.path as string) || 'user://mcp_dev_screenshot.png';
              if (!rawPath.startsWith('user://') && !rawPath.startsWith('res://')) {
                bridgeResult.screenshot = { success: false, error: 'path must start with user:// or res://' };
              } else if (hasTraversalSegments(rawPath)) {
                bridgeResult.screenshot = { success: false, error: 'path traversal blocked' };
              } else {
                const ssResp = await sendToBridge('take_screenshot', { path: rawPath }, 10000);
                bridgeResult.screenshot = ssResp.error
                  ? { success: false, error: ssResp.error.message }
                  : { success: true, ...(ssResp.result as Record<string, unknown>) };
              }
            }

            // Queries
            const queries = bridge.queries as Array<Record<string, unknown>> | undefined;
            if (queries && queries.length > 0) {
              const queryResults: Array<Record<string, unknown>> = [];
              for (const q of queries) {
                const method = q.method as string;
                if (!BRIDGE_READ_ONLY_METHODS.has(method)) {
                  queryResults.push({ method, success: false, error: `Method "${method}" not allowed in bridge queries. Allowed: ${[...BRIDGE_READ_ONLY_METHODS].join(', ')}` });
                  continue;
                }
                const params = (q.params as Record<string, unknown>) || {};
                const expect = q.expect as string | undefined;
                const qResp = await sendToBridge(method, params, 10000);
                if (qResp.error) {
                  queryResults.push({ method, success: false, error: qResp.error.message });
                } else {
                  const actual = JSON.stringify(qResp.result);
                  const match = expect ? actual.includes(expect) : undefined;
                  queryResults.push({ method, success: true, result: qResp.result, ...(expect !== undefined ? { match } : {}) });
                }
              }
              bridgeResult.queries = queryResults;
              if (queryResults.length > 0) {
                bridgeResult.all_queries_passed = queryResults.every(r => r.success !== false && (r.match === undefined || r.match === true));
              }
            }
          }
        } catch (err) {
          bridgeResult.error = err instanceof Error ? err.message : String(err);
        }
        const stepNum = verify ? 3 : 2;
        result[`step${stepNum}_bridge`] = bridgeResult;
      }

      // ── Acceptance assertions (execute individually for isolation) ──
      const rawAcceptance = args.acceptance;
      const acceptance = (rawAcceptance && typeof rawAcceptance === 'object' && !Array.isArray(rawAcceptance))
        ? rawAcceptance as Record<string, unknown>
        : undefined;
      if (acceptance) {
        ctx.progress?.(total, total, 'acceptance assertions'); // Task 4: acceptance=末步(=total)
        // ── frame_sequence: 自动捕获 N 帧到 proof 目录，供 frame_degradation 断言引用 ──
        let capturedFramesDir: string | undefined;
        let capturedRun: ProofRun | undefined; // B1:验证完成后清理 proof 临时目录
        const frameSeq = acceptance.frame_sequence as { count?: number; interval_frames?: number } | undefined;
        if (frameSeq && typeof frameSeq === 'object') {
          const count = Math.min(Math.max(Math.floor(frameSeq.count ?? 12), 2), 60);
          const interval = Math.min(Math.max(Math.floor(frameSeq.interval_frames ?? 10), 1), 300);
          try {
            const run = createProofRun(projectPath);
            let captureError: string | undefined;
            let captureWarning: string | undefined;
            // proof 目录在项目内；Bridge take_screenshot 路径必须 user:// 开头，先截到 user:// 再用 GDScript 归档
            for (let i = 0; i < count; i++) {
              const tmpPath = `user://mcp_frame_${i}.png`;
              const ssResp = await sendToBridge('take_screenshot', { path: tmpPath }, 10000);
              if (ssResp.error) { captureError = `frame ${i} 截图失败: ${ssResp.error.message ?? JSON.stringify(ssResp.error)}`; break; }
              // 通过 executeGdscript 把 user:// 的 PNG 字节读到 proof 目录（GDScript 函数体用 tab 缩进）
              const frameName = `frame_${String(i).padStart(2, '0')}.png`;
              const copyScript = `extends SceneTree
func _initialize():
	var img := Image.load_from_file("${tmpPath}")
	var f := FileAccess.open("${run.dir}/${frameName}", FileAccess.WRITE)
	f.store_buffer(img.save_png_to_buffer())
	quit()
`;
              // N2: 检查归档结果——失败则停止(防 proof 缺帧致 frame_degradation 误判)
              const copyResult = await executeGdscript({ godotPath: godot, projectPath, code: copyScript, timeout: Math.min(timeout, 15), loadAutoloads });
              if (!copyResult.compile_success || !copyResult.run_success) { captureError = `frame ${i} 归档失败: ${copyResult.compile_error || copyResult.run_error}`; break; }
              // N1: 配额累计(此路径用 GDScript 直写绕过 archiveFrame,需显式检查,防 60 帧撑爆磁盘)
              try { recordFrameBytes(run, join(run.dir, frameName)); }
              catch (e) { captureWarning = (e as Error).message; break; }
              if (i < count - 1) {
                // controller 预查无 _sleep 方法，改用 TS 侧 sleep（interval_frames × 16ms ≈ 60fps 间隔）
                await new Promise<void>(r => setTimeout(r, interval * 16));
              }
            }
            capturedFramesDir = run.dir;
            capturedRun = run;
            result.frame_sequence = { run_id: run.runId, dir: run.dir, count, ...(captureError ? { error: captureError } : {}), ...(captureWarning ? { warning: captureWarning } : {}) };
          } catch (err) {
            result.frame_sequence = { error: err instanceof Error ? err.message : String(err) };
          }
        }

        const assertionList = (acceptance.assertions as Array<Record<string, string>>) ?? [];
        if (assertionList.length > 0) {
          const assertionResults: Array<Record<string, unknown>> = [];

          for (let i = 0; i < assertionList.length; i++) {
            const a = assertionList[i]!;
            const desc = a.description ?? `assertion ${i}`;
            const assertType = (a as Record<string, unknown>).type as string || 'gdscript';

            // ── screenshot_diff assertion（真视觉对比）──
            if (assertType === 'screenshot_diff') {
              const validation = validateScreenshotAssertion(a as Record<string, unknown>);
              if (!validation.valid) {
                assertionResults.push({ description: desc, passed: false, error: validation.error });
                continue;
              }
              try {
                const ssResp = await sendToBridge('take_screenshot', { path: 'user://mcp_assert_screenshot.png' }, 10000);
                if (ssResp.error) {
                  assertionResults.push({ description: desc, passed: false, error: `Screenshot failed: ${ssResp.error.message ?? JSON.stringify(ssResp.error)}` });
                  continue;
                }
                const partials: string[] = [];

                // (a) reference 余弦相似度粗筛（若提供 reference_path）
                const rawReferencePath = (a as Record<string, unknown>).reference_path as string | undefined;
                if (rawReferencePath) {
                  // B5:reference_path 限 res://、user:// 或项目内绝对路径,防项目外任意文件读取
                  let referencePath: string;
                  if (rawReferencePath.startsWith('res://') || rawReferencePath.startsWith('user://')) {
                    if (hasTraversalSegments(rawReferencePath)) {
                      assertionResults.push({ description: desc, passed: false, error: 'path traversal blocked' });
                      continue;
                    }
                    referencePath = rawReferencePath;
                  } else {
                    try { referencePath = resolveWithinRoot(projectPath, rawReferencePath); }
                    catch { assertionResults.push({ description: desc, passed: false, error: `reference_path 越出项目根目录: ${rawReferencePath}` }); continue; }
                  }
                  // N3: sim_threshold 运行时类型校验(裸 as 对字符串值无效,致 sim < 字符串得 NaN 放行)
                  const rawSimThreshold = (a as Record<string, unknown>).sim_threshold;
                  const simThreshold = typeof rawSimThreshold === 'number' && Number.isFinite(rawSimThreshold) ? rawSimThreshold : 0.85;
                  const simResult = await executeGdscript({
                    godotPath: godot, projectPath,
                    code: referenceSimScript('user://mcp_assert_screenshot.png', referencePath),
                    timeout: Math.min(timeout, 15), loadAutoloads,
                  });
                  if (!simResult.compile_success || !simResult.run_success) {
                    assertionResults.push({ description: desc, passed: false, error: `reference sim failed: ${simResult.compile_error || simResult.run_error}` });
                    continue;
                  }
                  const sim = Number(simResult.outputs.find(e => e.key === 'reference_sim')?.value ?? -1);
                  partials.push(`reference_sim=${sim.toFixed(3)} (threshold ${simThreshold})`);
                  if (sim < simThreshold) {
                    assertionResults.push({ description: desc, passed: false, actual: partials.join('; '), expected: `reference_sim >= ${simThreshold}` });
                    continue;
                  }
                }

                // (b) 真可见性检查（替代旧 get_tree + includes 假检查）
                const expectPresent = (a as Record<string, unknown>).expect_present as string[] | undefined;
                if (expectPresent && expectPresent.length > 0) {
                  const visResp = await sendToBridge('find_ui_elements', { pattern: '*', visible_only: true, limit: 500 }, 10000);
                  if (visResp.error) {
                    assertionResults.push({ description: desc, passed: false, error: `find_ui_elements failed: ${visResp.error.message ?? JSON.stringify(visResp.error)}` });
                    continue;
                  }
                  const visStr = JSON.stringify(visResp);
                  const missing = expectPresent.filter(name => !visStr.includes(name));
                  if (missing.length > 0) {
                    assertionResults.push({ description: desc, passed: false, actual: `missing visible: ${missing.join(', ')}`, expected: `all visible: ${expectPresent.join(', ')}` });
                    continue;
                  }
                  partials.push(`visible: ${expectPresent.join(', ')}`);
                }

                assertionResults.push({ description: desc, passed: true, actual: partials.join('; ') || 'screenshot captured' });
              } catch (err) {
                assertionResults.push({ description: desc, passed: false, error: err instanceof Error ? err.message : String(err) });
              }
              continue;
            }

            // ── frame_degradation assertion（帧退化检测，Godogen 灵魂）──
            if (assertType === 'frame_degradation') {
              const fd = a as Record<string, unknown>;
              if (typeof fd.description !== 'string') {
                assertionResults.push({ description: 'frame_degradation', passed: false, error: 'requires description' });
                continue;
              }
              // 若断言未提供 frames_dir 但 frame_sequence 已捕获，自动复用
              const rawFramesDir = (fd.frames_dir as string | undefined) ?? capturedFramesDir;
              if (!rawFramesDir) {
                assertionResults.push({ description: fd.description, passed: false, error: 'frame_degradation requires frames_dir or acceptance.frame_sequence to capture frames first' });
                continue;
              }
              // B5:frames_dir 限 res://、user:// 或项目内绝对路径
              let framesDir: string;
              if (rawFramesDir.startsWith('res://') || rawFramesDir.startsWith('user://')) {
                if (hasTraversalSegments(rawFramesDir)) {
                  assertionResults.push({ description: fd.description, passed: false, error: 'path traversal blocked' });
                  continue;
                }
                framesDir = rawFramesDir;
              } else {
                try { framesDir = resolveWithinRoot(projectPath, rawFramesDir); }
                catch { assertionResults.push({ description: fd.description, passed: false, error: `frames_dir 越出项目根目录: ${rawFramesDir}` }); continue; }
              }
              try {
                const metricsResult = await executeGdscript({
                  godotPath: godot, projectPath,
                  code: extractFrameMetricsScript(framesDir),
                  timeout: Math.min(timeout, 30), loadAutoloads,
                });
                if (!metricsResult.compile_success || !metricsResult.run_success) {
                  assertionResults.push({ description: fd.description, passed: false, error: `metrics extraction failed: ${metricsResult.compile_error || metricsResult.run_error}` });
                  continue;
                }
                const out = (key: string) => metricsResult.outputs.find(e => e.key === key)?.value;
                const frameCount = Number(out('frame_count') ?? 0);
                // Task 4 协议：consecutive_sims/first_frame_sims 是 JSON.stringify 字符串，需还原
                const consecutive = JSON.parse(String(out('consecutive_sims') ?? '[]')) as number[];
                const firstFrame = JSON.parse(String(out('first_frame_sims') ?? '[]')) as number[];
                const verdict = classifyDegradation({ frameCount, consecutiveSims: consecutive, firstFrameSims: firstFrame } as FrameMetrics);
                assertionResults.push({
                  description: fd.description,
                  passed: !verdict.degraded,
                  actual: verdict.degraded ? `DEGRADED: ${verdict.reason}` : `healthy (meanConsecutive=${verdict.metrics.meanConsecutive.toFixed(3)}, maxChange=${verdict.metrics.maxChange.toFixed(3)})`,
                  expected: 'frames show real motion (not identical/stalled)',
                });
              } catch (err) {
                assertionResults.push({ description: fd.description, passed: false, error: err instanceof Error ? err.message : String(err) });
              }
              continue;
            }

            // ── default: gdscript assertion ──
            if (typeof a.gdscript !== 'string' || !a.gdscript.trim()) {
              assertionResults.push({ description: desc, passed: false, error: 'Missing required "gdscript" field in assertion' });
              continue;
            }
            try {
              const wrappedCode = wrapAssertionCode(a.gdscript, desc, true, a.expect);
              // B-1(2026-09-11 审查): wrappedCode 内联 SCENE_TREE_HEADER(含 load(_sp) 模板)——
              // 普通通道 Phase 3(tokenizer 非字面量 load)必拦。切 Runtime 通道(delivery.ts 同款):
              // 只跳 Phase 3,Phase 1/2 保留;AI 原始 assertion 代码已有 wrapAssertionCode 内的
              // 前置 scanGdscriptSandbox 全相位扫描兜底(assertions.ts)。
              const assertResult = await executeGdscriptRuntime({
                godotPath: godot, projectPath, code: wrappedCode, timeout: Math.min(timeout, 15), loadAutoloads,
              });

              if (!assertResult.compile_success) {
                assertionResults.push({ description: desc, passed: false, error: assertResult.compile_error });
              } else if (!assertResult.run_success) {
                assertionResults.push({ description: desc, passed: false, error: assertResult.run_error });
              } else {
                const actual = String(assertResult.outputs.find(e => e.key.startsWith('assert_') || e.key === 'assert_result')?.value ?? '');
                const passed = a.expect ? actual === a.expect : true;
                assertionResults.push({ description: desc, passed, actual, expected: a.expect });
              }
            } catch (err) {
              assertionResults.push({ description: desc, passed: false, error: err instanceof Error ? err.message : String(err) });
            }
          }

          // B1:验证完成后清理 frame_sequence 捕获的 proof 临时目录(防 proof/ 无限堆积)
          if (capturedRun) cleanupProofRun(capturedRun);

          result.acceptance = {
            passed: assertionResults.every(r => r.passed),
            results: assertionResults,
          };
        }
      }

      // ── Step 5: Save State (optional, file-as-memory pattern) ──
      if (args.save_state && typeof args.save_state === 'object') {
        const ss = args.save_state as Record<string, unknown>;
        const statePath = (ss.path as string) || 'production/session-state/active.md';
        const fullStatePath = resolveWithinRoot(projectPath, statePath);
        const dir = dirname(fullStatePath);
        mkdirSync(dir, { recursive: true });
        const content = formatSessionState({
          current_task: (ss.task as string) || 'Unknown task',
          epic: ss.epic as string | undefined,
          feature: ss.feature as string | undefined,
          files_modified: ss.files_modified as string[] | undefined,
          decisions: ss.decisions as string[] | undefined,
          open_questions: ss.open_questions as string[] | undefined,
        });
        writeFileSync(fullStatePath, content, 'utf-8');
        result.save_state = { saved: true, path: statePath };
      }

      return textResult(JSON.stringify(result, null, 2));
    }

    case 'scene_snapshot': {
      const projectPath = requireProjectPath(args);
      const scenePath = args.scene_path as string;
      // I-3: scene_path 非空校验,避免 undefined.startsWith 抛 TypeError 返回不友好错误
      if (!scenePath) {
        return textResult('Error: "scene_path" is required for scene_snapshot.');
      }
      // M-3: 校验 scene_path 在项目内（防 ../ 逃逸读项目外 .tscn；:657 仅补 res:// 前缀不防穿越，read 级信息泄露）
      try { resolveWithinRoot(projectPath, normalizeUserProjectPath(scenePath)); } catch { return opsErrorResult('INVALID_PATH', 'scene_path contains path traversal'); }
      const maxDepth = (args.max_depth as number) || 5;
      const godot = await ctx.findGodot();

      // Ensure res:// prefix for load() — sandbox allows only res:// paths
      const resPath = scenePath.startsWith('res://') ? scenePath : 'res://' + scenePath.replace(/\\/g, '/');
      // T2b: resPath 只内嵌进纯字符串字面量(genSceneSnapshotScript 的 load()/错误消息),
      // 不参与 % 格式化——escapeForGdLiteral(含 % 的场景文件名在文件系统层合法)。
      const safePath = escapeForGdLiteral(resPath);
      const snapScript = genSceneSnapshotScript(safePath, maxDepth);

      const result = await executeGdscriptTrusted({
        godotPath: godot,
        projectPath,
        code: snapScript,
        timeout: 30,
        loadAutoloads: false,
      });

      return parseGdscriptResult(result, [], () => 'SNAPSHOT_FAILED');
    }

    case 'batch_validate': {
      const projectPath = requireProjectPath(args);
      const scripts = args.scripts as string[];

      if (!scripts || !Array.isArray(scripts) || scripts.length === 0) {
        return opsErrorResult('INVALID_PARAMS', '"scripts" must be a non-empty array of file paths.');
      }

      const godot = await ctx.findGodot();
      const fullPaths: string[] = [];
      const missing: string[] = [];

      for (const s of scripts) {
        // A6: resolveWithinRoot 越权防护（替代裸 join，防 existsSync 信息泄露）。
        // normalizeUserProjectPath 剥 res:// 前缀，resolveWithinRoot 校验 .. 段。
        const full = resolveWithinRoot(projectPath, normalizeUserProjectPath(s));
        if (existsSync(full)) {
          fullPaths.push(full);
        } else {
          missing.push(s);
        }
      }

      const batchResults = await batchValidateScripts(godot, projectPath, fullPaths, 15000);

      const results: Record<string, unknown> = {};
      let allValid = true;
      let totalFiltered = 0;

      for (const r of batchResults) {
        results[r.file] = r.errors.length > 0 ? { valid: false, error: r.errors } : { valid: true };
        if (r.errors.length > 0) allValid = false;
        if (r.filtered_count) totalFiltered += r.filtered_count;
      }
      for (const m of missing) {
        results[m] = { valid: false, error: 'File not found' };
        allValid = false;
      }

      const summary: Record<string, unknown> = { all_valid: allValid, total: scripts.length, results };
      if (totalFiltered > 0) summary.filtered_count = totalFiltered;

      return textResult(JSON.stringify(summary, null, 2));
    }

    case 'create_files':
    case 'run_verify':
    case 'diff_scenes':
      return handleBatchAction(action, args, ctx);

    default:
      return textResult(`Unknown action: ${action}. Use "dev_loop", "scene_snapshot", or "batch_validate".`);
  }
}


// --- Helpers -------------------------------------------------------------------

async function runVerification(godot: string, projectPath: string): Promise<Record<string, unknown>> {
  const result = await spawnGodot(godot, ['--headless', '--path', projectPath, '-e', '--quit'], {
    timeoutMs: 20_000,
  });

  if (result.timedOut) {
    return { status: 'timeout', output: result.stdout.slice(-2000) };
  }

  if (result.exitCode === -1 && result.stdout.includes('Error:')) {
    return { status: 'error', message: result.stdout.split('\n').pop()!.replace('Error: ', '') };
  }

  const errors = result.stdout.split('\n').filter(l => l.includes('ERROR') || l.includes('SCRIPT ERROR'));
  return {
    status: result.exitCode === 0 ? 'passed' : 'failed',
    exit_code: result.exitCode,
    error_count: errors.length,
    errors: errors.slice(0, 10),
  };
}


// ─── E2E DSL parser ────────────────────────────────────────────────────────────

interface DslCommand {
  method: string;
  params: Record<string, unknown>;
}

const DSL_ERROR = (msg: string): DslCommand => ({ method: '_error', params: { message: msg } });
// eslint-disable-next-line no-control-regex
const CTRL_RE = /[\x00-\x08\x0B\x0C\x0E-\x1F]/; // exclude \t \n \r

export function parseE2eDsl(line: string): DslCommand | null {
  const trimmed = line.trim();
  if (!trimmed) return null;

  // waitFor("path")
  const waitMatch = trimmed.match(/^waitFor\(\s*"([^"]+)"\s*\)$/);
  if (waitMatch) {
    const path = waitMatch[1]!;
    if (path.length > 1024) return DSL_ERROR(`waitFor: path exceeds 1024 chars (${path.length})`);
    if (CTRL_RE.test(path)) return DSL_ERROR(`waitFor: path contains control characters`);
    if (!/^root(\/[\w.-]+)+$/.test(path)) return DSL_ERROR(`waitFor: invalid path "${path}" — must be root/X/Y format with alphanumeric, dot, or hyphen segments`);
    return { method: 'wait_for_node', params: { path } };
  }

  // click(x, y[, "button"])
  const clickMatch = trimmed.match(/^click\(\s*(-?\d+)\s*,\s*(-?\d+)\s*(?:,\s*"(\w+)")?\s*\)$/);
  if (clickMatch) {
    const x = Number(clickMatch[1]);
    const y = Number(clickMatch[2]);
    const button = clickMatch[3] || 'left';
    if (x < 0 || x > 10000) return DSL_ERROR(`click: x=${x} out of range [0, 10000]`);
    if (y < 0 || y > 10000) return DSL_ERROR(`click: y=${y} out of range [0, 10000]`);
    if (!['left', 'right', 'middle'].includes(button)) return DSL_ERROR(`click: invalid button "${button}" — must be left, right, or middle`);
    return { method: 'send_mouse_click', params: { x, y, button, pressed: true } };
  }

  // press("key")
  const pressMatch = trimmed.match(/^press\(\s*"([^"]*)"\s*\)$/);
  if (pressMatch) {
    const key = pressMatch[1];
    if (!key) return DSL_ERROR(`press: empty key name`);
    if (key.length > 64) return DSL_ERROR(`press: key name exceeds 64 chars`);
    if (!/^[\w ]+$/.test(key)) return DSL_ERROR(`press: invalid key name "${key}" — only alphanumeric, underscore, space allowed`);
    return { method: 'send_key', params: { key, pressed: true } };
  }

  // typeText("text")
  const typeMatch = trimmed.match(/^typeText\(\s*"([^"]*)"\s*\)$/);
  if (typeMatch) {
    const text = typeMatch[1]!;
    if (text.length > 512) return DSL_ERROR(`typeText: text exceeds 512 chars (${text.length})`);
    if (CTRL_RE.test(text)) return DSL_ERROR(`typeText: text contains control characters`);
    return { method: 'send_text', params: { text } };
  }

  // waitMs(ms)
  const sleepMatch = trimmed.match(/^waitMs\(\s*(\d+)\s*\)$/);
  if (sleepMatch) {
    const ms = Number(sleepMatch[1]);
    if (ms < 0 || ms > 60000) return DSL_ERROR(`waitMs: ${ms}ms out of range [0, 60000]`);
    return { method: '_sleep', params: { ms } };
  }

  return null;
}

// ─── Screenshot diff assertion validation ─────────────────────────────────────

export function validateScreenshotAssertion(
  assertion: Record<string, unknown>,
): { valid: boolean; error?: string } {
  if (!assertion.description || typeof assertion.description !== 'string') {
    return { valid: false, error: 'screenshot_diff assertion requires a description field' };
  }
  const ep = assertion.expect_present;
  if (ep !== undefined && !Array.isArray(ep)) {
    return { valid: false, error: 'expect_present must be a string array' };
  }
  const rp = assertion.reference_path;
  if (rp !== undefined && typeof rp !== 'string') {
    return { valid: false, error: 'reference_path must be a string' };
  }
  const st = assertion.sim_threshold;
  if (st !== undefined && (typeof st !== 'number' || st < 0 || st > 1)) {
    return { valid: false, error: 'sim_threshold must be a number in [0, 1]' };
  }
  return { valid: true };
}

export const TOOL_META: Record<string, { readonly: boolean; long_running: boolean; actionRisks?: Record<string, RiskLevel> }> = {
  workflow: {
    readonly: false,
    long_running: true,
    actionRisks: {
      scene_snapshot: 'read',
      batch_validate: 'read',
      diff_scenes: 'read',
      dev_loop: 'process',
      run_verify: 'process',
      create_files: 'write',
    } satisfies Record<typeof ACTIONS[number], RiskLevel>,
  },
  // 旧工具名 batch 的 TOOL_META 条目已删(2026-08-21 七维度审核 P3):v0.18 合并后残留使
  // getAllToolNames() 返回 49 而非 45,污染 isKnownTool/动态注册判定;旧名映射职责在
  // tool-registry 的 LEGACY_TOOL_MAP。
};
